name: Ejecutar download_pdf.js diariamente

on:
  schedule:
    - cron: '0 16 * * *'  # 12:00 Chile (UTC-4)
  workflow_dispatch:       # Permite ejecución manual

jobs:
  run-download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          cd backend
          npm install

      - name: Ejecutar script download_pdf.js
        run: |
          cd backend
          node models/download_pdf.js
