name: Ejecutar extract_and_upload.js diariamente

on:
  schedule:
    - cron: '30 16 * * *'  # 12:30 Chile = 16:30 UTC
  workflow_dispatch:

jobs:
  run-extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Crear archivo de credenciales desde secreto
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > backend/vertex-key.json

      - name: Establecer GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=./vertex-key.json" >> $GITHUB_ENV
        working-directory: backend

      - name: Instalar dependencias
        run: npm install
        working-directory: backend

      - name: Ejecutar script extract_and_upload.js
        run: node models/extract_and_upload.js
        working-directory: backend
